model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_adaptive_v2
ablate:
- layer: 0
  measurement: 0
  scale: 1.2
  sparsity: 0.03
- layer: 0
  measurement: composite
  scale: 2.4
  sparsity: 0.03
- layer: 1
  measurement: 1
  scale: 1.2
  sparsity: 0.03
- layer: 1
  measurement: composite
  scale: 2.4
  sparsity: 0.03
- layer: 2
  measurement: 2
  scale: 1.2
  sparsity: 0.03
- layer: 2
  measurement: composite
  scale: 2.4
  sparsity: 0.03
- layer: 3
  measurement: 3
  scale: 1.948
  sparsity: 0.03
- layer: 3
  measurement: composite
  scale: 3.896
  sparsity: 0.03
- layer: 4
  measurement: 4
  scale: 3.445
  sparsity: 0.03
- layer: 4
  measurement: composite
  scale: 6.89
  sparsity: 0.03
- layer: 5
  measurement: 5
  scale: 4.77
  sparsity: 0.03
- layer: 5
  measurement: composite
  scale: 9.54
  sparsity: 0.03
- layer: 6
  measurement: 6
  scale: 5.205
  sparsity: 0.03
- layer: 6
  measurement: composite
  scale: 10.41
  sparsity: 0.03
- layer: 7
  measurement: 7
  scale: 6.373
  sparsity: 0.03
- layer: 7
  measurement: composite
  scale: 12.746
  sparsity: 0.03
- layer: 8
  measurement: 8
  scale: 6.109
  sparsity: 0.03
- layer: 8
  measurement: composite
  scale: 12.218
  sparsity: 0.03
- layer: 9
  measurement: 9
  scale: 6.572
  sparsity: 0.03
- layer: 9
  measurement: composite
  scale: 13.144
  sparsity: 0.03
- layer: 10
  measurement: 10
  scale: 7.0
  sparsity: 0.03
- layer: 10
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 11
  measurement: 11
  scale: 7.0
  sparsity: 0.03
- layer: 11
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 12
  measurement: 12
  scale: 7.0
  sparsity: 0.03
- layer: 12
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 13
  measurement: 13
  scale: 7.0
  sparsity: 0.03
- layer: 13
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 14
  measurement: 14
  scale: 7.0
  sparsity: 0.03
- layer: 14
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 15
  measurement: 15
  scale: 7.0
  sparsity: 0.03
- layer: 15
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 16
  measurement: 16
  scale: 7.0
  sparsity: 0.03
- layer: 16
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 17
  measurement: 17
  scale: 6.738
  sparsity: 0.03
- layer: 17
  measurement: composite
  scale: 13.476
  sparsity: 0.03
- layer: 18
  measurement: 18
  scale: 7.0
  sparsity: 0.03
- layer: 18
  measurement: composite
  scale: 14.0
  sparsity: 0.03
- layer: 19
  measurement: 19
  scale: 6.235
  sparsity: 0.03
- layer: 19
  measurement: composite
  scale: 12.47
  sparsity: 0.03
- layer: 20
  measurement: 20
  scale: 6.665
  sparsity: 0.03
- layer: 20
  measurement: composite
  scale: 13.33
  sparsity: 0.03
- layer: 21
  measurement: 21
  scale: 5.311
  sparsity: 0.03
- layer: 21
  measurement: composite
  scale: 10.622
  sparsity: 0.03
- layer: 22
  measurement: 22
  scale: 4.896
  sparsity: 0.03
- layer: 22
  measurement: composite
  scale: 9.792
  sparsity: 0.03
- layer: 23
  measurement: 23
  scale: 3.533
  sparsity: 0.03
- layer: 23
  measurement: composite
  scale: 7.066
  sparsity: 0.03
