model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router_strong
targets:
- mlp.router.weight
- mlp.router.bias
ablate:
- layer: 0
  measurement: 0
  scale: 1.026
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 2.052
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 1.421
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 2.843
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 2.17
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 4.339
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 3.168
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 6.336
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 4.289
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 8.579
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 5.282
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 10.565
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 5.608
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 11.216
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 6.483
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 12.966
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 6.285
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 12.57
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 6.632
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 13.264
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 7.54
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 15.081
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 7.033
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 14.066
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 7.182
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 14.364
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 7.111
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 14.222
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 7.994
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 15.989
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 7.134
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 14.267
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 8.0
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 16.0
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 6.756
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 13.512
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 6.995
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 13.991
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 6.38
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 12.76
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 6.702
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 13.404
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 5.687
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 11.374
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 5.376
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 10.753
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 4.355
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 8.71
  sparsity: 0.05
