model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router
targets:
- mlp.router.weight
- mlp.router.bias
ablate:
- layer: 0
  measurement: 0
  scale: 1.0
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 2.0
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 1.0
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 2.0
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 1.0
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 2.0
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 1.516
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 3.032
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 2.548
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 5.096
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 3.462
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 6.924
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 3.762
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 7.524
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 4.567
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 9.134
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 4.385
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 8.77
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 4.705
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 9.41
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 5.0
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 5.0
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 5.0
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 5.0
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 5.0
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 5.0
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 5.0
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 4.819
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 9.638
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 5.0
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 10.0
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 4.473
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 8.946
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 4.769
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 9.538
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 3.835
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 7.67
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 3.549
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 7.098
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 2.609
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 5.218
  sparsity: 0.05
