model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router_exps_moderate
targets:
- mlp.router.weight
- mlp.router.bias
- mlp.experts.gate_up_proj_blocks
- mlp.experts.down_proj_blocks
- mlp.experts.gate_up_proj_bias
- mlp.experts.down_proj_bias
- mlp.experts.gate_proj.weight
- mlp.experts.up_proj.weight
- mlp.experts.down_proj.weight
ablate:
- layer: 0
  measurement: 0
  scale: 0.898
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 1.796
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 1.244
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 2.487
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 1.898
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 3.797
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 2.772
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 5.544
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 3.753
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 7.506
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 4.622
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 9.244
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 4.907
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 9.814
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 5.672
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 11.345
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 5.499
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 10.999
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 5.803
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 11.606
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 6.598
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 13.195
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 6.154
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 12.308
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 6.284
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 12.569
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 6.222
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 12.444
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 6.995
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 13.99
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 6.242
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 12.484
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 7.0
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 14.0
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 5.912
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 11.823
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 6.121
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 12.242
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 5.582
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 11.165
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 5.864
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 11.728
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 4.976
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 9.952
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 4.704
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 9.409
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 3.811
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 7.621
  sparsity: 0.05
