model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_adaptive
ablate:
- layer: 0
  measurement: 0
  scale: 1.0
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 1.8
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 1.0
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 1.8
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 1.0
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 1.8
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 1.0
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 1.8
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 1.624
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 2.923
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 2.385
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 4.293
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 2.635
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 4.743
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 3.306
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 5.951
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 3.154
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 5.677
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 3.42
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 6.156
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 4.117
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 7.411
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 3.728
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 6.71
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 3.843
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 6.917
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 3.788
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 6.818
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 4.466
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 8.039
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 3.805
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 6.849
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 4.47
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 8.046
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 3.516
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 6.329
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 3.699
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 6.658
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 3.227
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 5.809
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 3.474
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 6.253
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 2.696
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 4.853
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 2.457
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 4.423
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 1.674
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 3.013
  sparsity: 0.05
