model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router_exps_base2p5
targets:
- mlp.router.weight
- mlp.router.bias
- mlp.experts.gate_up_proj_blocks
- mlp.experts.down_proj_blocks
- mlp.experts.gate_up_proj_bias
- mlp.experts.down_proj_bias
- mlp.experts.gate_proj.weight
- mlp.experts.up_proj.weight
- mlp.experts.down_proj.weight
ablate:
- layer: 0
  measurement: 0
  scale: 0.321
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 0.641
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 0.444
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 0.888
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 0.678
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 1.356
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 0.99
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 1.98
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 1.34
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 2.681
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 1.651
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 3.301
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 1.752
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 3.505
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 2.026
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 4.052
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 1.964
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 3.928
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 2.072
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 4.145
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 2.356
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 4.713
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 2.198
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 4.396
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 2.244
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 4.489
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 2.222
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 4.444
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 2.498
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 4.997
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 2.229
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 4.458
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 2.5
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 5.0
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 2.111
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 4.223
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 2.186
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 4.372
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 1.994
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 3.987
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 2.094
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 4.189
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 1.777
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 3.554
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 1.68
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 3.36
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 1.361
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 2.722
  sparsity: 0.05
