model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router_exps_strong
targets:
- mlp.router.weight
- mlp.router.bias
- mlp.experts.gate_up_proj_blocks
- mlp.experts.down_proj_blocks
- mlp.experts.gate_up_proj_bias
- mlp.experts.down_proj_bias
- mlp.experts.gate_proj.weight
- mlp.experts.up_proj.weight
- mlp.experts.down_proj.weight
ablate:
- layer: 0
  measurement: 0
  scale: 1.283
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 2.565
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 1.777
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 3.553
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 2.712
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 5.424
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 3.96
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 7.92
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 5.362
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 10.723
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 6.603
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 13.206
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 7.01
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 14.02
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 8.104
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 16.207
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 7.856
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 15.712
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 8.29
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 16.58
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 9.425
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 18.851
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 8.791
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 17.582
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 8.978
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 17.955
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 8.889
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 17.777
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 9.993
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 19.986
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 8.917
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 17.834
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 10.0
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 20.0
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 8.445
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 16.89
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 8.744
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 17.488
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 7.975
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 15.95
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 8.377
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 16.754
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 7.109
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 14.218
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 6.72
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 13.441
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 5.444
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 10.888
  sparsity: 0.05
