model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router_exps_base0p5_sp0p8
targets:
- mlp.router.weight
- mlp.router.bias
- mlp.experts.gate_up_proj_blocks
- mlp.experts.down_proj_blocks
- mlp.experts.gate_up_proj_bias
- mlp.experts.down_proj_bias
- mlp.experts.gate_proj.weight
- mlp.experts.up_proj.weight
- mlp.experts.down_proj.weight
ablate:
- layer: 0
  measurement: 0
  scale: 0.064
  sparsity: 0.8
- layer: 0
  measurement: composite
  scale: 0.128
  sparsity: 0.8
- layer: 1
  measurement: 1
  scale: 0.089
  sparsity: 0.8
- layer: 1
  measurement: composite
  scale: 0.178
  sparsity: 0.8
- layer: 2
  measurement: 2
  scale: 0.136
  sparsity: 0.8
- layer: 2
  measurement: composite
  scale: 0.271
  sparsity: 0.8
- layer: 3
  measurement: 3
  scale: 0.198
  sparsity: 0.8
- layer: 3
  measurement: composite
  scale: 0.396
  sparsity: 0.8
- layer: 4
  measurement: 4
  scale: 0.268
  sparsity: 0.8
- layer: 4
  measurement: composite
  scale: 0.536
  sparsity: 0.8
- layer: 5
  measurement: 5
  scale: 0.33
  sparsity: 0.8
- layer: 5
  measurement: composite
  scale: 0.66
  sparsity: 0.8
- layer: 6
  measurement: 6
  scale: 0.35
  sparsity: 0.8
- layer: 6
  measurement: composite
  scale: 0.701
  sparsity: 0.8
- layer: 7
  measurement: 7
  scale: 0.405
  sparsity: 0.8
- layer: 7
  measurement: composite
  scale: 0.81
  sparsity: 0.8
- layer: 8
  measurement: 8
  scale: 0.393
  sparsity: 0.8
- layer: 8
  measurement: composite
  scale: 0.786
  sparsity: 0.8
- layer: 9
  measurement: 9
  scale: 0.414
  sparsity: 0.8
- layer: 9
  measurement: composite
  scale: 0.829
  sparsity: 0.8
- layer: 10
  measurement: 10
  scale: 0.471
  sparsity: 0.8
- layer: 10
  measurement: composite
  scale: 0.943
  sparsity: 0.8
- layer: 11
  measurement: 11
  scale: 0.44
  sparsity: 0.8
- layer: 11
  measurement: composite
  scale: 0.879
  sparsity: 0.8
- layer: 12
  measurement: 12
  scale: 0.449
  sparsity: 0.8
- layer: 12
  measurement: composite
  scale: 0.898
  sparsity: 0.8
- layer: 13
  measurement: 13
  scale: 0.444
  sparsity: 0.8
- layer: 13
  measurement: composite
  scale: 0.889
  sparsity: 0.8
- layer: 14
  measurement: 14
  scale: 0.5
  sparsity: 0.8
- layer: 14
  measurement: composite
  scale: 0.999
  sparsity: 0.8
- layer: 15
  measurement: 15
  scale: 0.446
  sparsity: 0.8
- layer: 15
  measurement: composite
  scale: 0.892
  sparsity: 0.8
- layer: 16
  measurement: 16
  scale: 0.5
  sparsity: 0.8
- layer: 16
  measurement: composite
  scale: 1.0
  sparsity: 0.8
- layer: 17
  measurement: 17
  scale: 0.422
  sparsity: 0.8
- layer: 17
  measurement: composite
  scale: 0.845
  sparsity: 0.8
- layer: 18
  measurement: 18
  scale: 0.437
  sparsity: 0.8
- layer: 18
  measurement: composite
  scale: 0.874
  sparsity: 0.8
- layer: 19
  measurement: 19
  scale: 0.399
  sparsity: 0.8
- layer: 19
  measurement: composite
  scale: 0.797
  sparsity: 0.8
- layer: 20
  measurement: 20
  scale: 0.419
  sparsity: 0.8
- layer: 20
  measurement: composite
  scale: 0.838
  sparsity: 0.8
- layer: 21
  measurement: 21
  scale: 0.355
  sparsity: 0.8
- layer: 21
  measurement: composite
  scale: 0.711
  sparsity: 0.8
- layer: 22
  measurement: 22
  scale: 0.336
  sparsity: 0.8
- layer: 22
  measurement: composite
  scale: 0.672
  sparsity: 0.8
- layer: 23
  measurement: 23
  scale: 0.272
  sparsity: 0.8
- layer: 23
  measurement: composite
  scale: 0.544
  sparsity: 0.8
