model: outputs/gpt_oss_dequant
measurements: outputs/gpt_oss_dequant_chattemp.refuse.pt
output: outputs/gpt_oss_dequant_ablated_chattemp_router_exps_base1
targets:
- mlp.router.weight
- mlp.router.bias
- mlp.experts.gate_up_proj_blocks
- mlp.experts.down_proj_blocks
- mlp.experts.gate_up_proj_bias
- mlp.experts.down_proj_bias
- mlp.experts.gate_proj.weight
- mlp.experts.up_proj.weight
- mlp.experts.down_proj.weight
ablate:
- layer: 0
  measurement: 0
  scale: 0.128
  sparsity: 0.05
- layer: 0
  measurement: composite
  scale: 0.257
  sparsity: 0.05
- layer: 1
  measurement: 1
  scale: 0.178
  sparsity: 0.05
- layer: 1
  measurement: composite
  scale: 0.355
  sparsity: 0.05
- layer: 2
  measurement: 2
  scale: 0.271
  sparsity: 0.05
- layer: 2
  measurement: composite
  scale: 0.542
  sparsity: 0.05
- layer: 3
  measurement: 3
  scale: 0.396
  sparsity: 0.05
- layer: 3
  measurement: composite
  scale: 0.792
  sparsity: 0.05
- layer: 4
  measurement: 4
  scale: 0.536
  sparsity: 0.05
- layer: 4
  measurement: composite
  scale: 1.072
  sparsity: 0.05
- layer: 5
  measurement: 5
  scale: 0.66
  sparsity: 0.05
- layer: 5
  measurement: composite
  scale: 1.321
  sparsity: 0.05
- layer: 6
  measurement: 6
  scale: 0.701
  sparsity: 0.05
- layer: 6
  measurement: composite
  scale: 1.402
  sparsity: 0.05
- layer: 7
  measurement: 7
  scale: 0.81
  sparsity: 0.05
- layer: 7
  measurement: composite
  scale: 1.621
  sparsity: 0.05
- layer: 8
  measurement: 8
  scale: 0.786
  sparsity: 0.05
- layer: 8
  measurement: composite
  scale: 1.571
  sparsity: 0.05
- layer: 9
  measurement: 9
  scale: 0.829
  sparsity: 0.05
- layer: 9
  measurement: composite
  scale: 1.658
  sparsity: 0.05
- layer: 10
  measurement: 10
  scale: 0.943
  sparsity: 0.05
- layer: 10
  measurement: composite
  scale: 1.885
  sparsity: 0.05
- layer: 11
  measurement: 11
  scale: 0.879
  sparsity: 0.05
- layer: 11
  measurement: composite
  scale: 1.758
  sparsity: 0.05
- layer: 12
  measurement: 12
  scale: 0.898
  sparsity: 0.05
- layer: 12
  measurement: composite
  scale: 1.796
  sparsity: 0.05
- layer: 13
  measurement: 13
  scale: 0.889
  sparsity: 0.05
- layer: 13
  measurement: composite
  scale: 1.778
  sparsity: 0.05
- layer: 14
  measurement: 14
  scale: 0.999
  sparsity: 0.05
- layer: 14
  measurement: composite
  scale: 1.999
  sparsity: 0.05
- layer: 15
  measurement: 15
  scale: 0.892
  sparsity: 0.05
- layer: 15
  measurement: composite
  scale: 1.783
  sparsity: 0.05
- layer: 16
  measurement: 16
  scale: 1.0
  sparsity: 0.05
- layer: 16
  measurement: composite
  scale: 2.0
  sparsity: 0.05
- layer: 17
  measurement: 17
  scale: 0.845
  sparsity: 0.05
- layer: 17
  measurement: composite
  scale: 1.689
  sparsity: 0.05
- layer: 18
  measurement: 18
  scale: 0.874
  sparsity: 0.05
- layer: 18
  measurement: composite
  scale: 1.749
  sparsity: 0.05
- layer: 19
  measurement: 19
  scale: 0.797
  sparsity: 0.05
- layer: 19
  measurement: composite
  scale: 1.595
  sparsity: 0.05
- layer: 20
  measurement: 20
  scale: 0.838
  sparsity: 0.05
- layer: 20
  measurement: composite
  scale: 1.675
  sparsity: 0.05
- layer: 21
  measurement: 21
  scale: 0.711
  sparsity: 0.05
- layer: 21
  measurement: composite
  scale: 1.422
  sparsity: 0.05
- layer: 22
  measurement: 22
  scale: 0.672
  sparsity: 0.05
- layer: 22
  measurement: composite
  scale: 1.344
  sparsity: 0.05
- layer: 23
  measurement: 23
  scale: 0.544
  sparsity: 0.05
- layer: 23
  measurement: composite
  scale: 1.089
  sparsity: 0.05
